python run.py \
--gpu 0 \
--data_path ./aircraft_npys \
--loader AirCraft \
--task GeoPT_finetune \
--dynamics craft \
--geotype unstructured \
--space_dim 3 \
--fun_dim 11 \
--out_dim 6 \
--normalize 1 \
--model Transolver \
--n_hidden 256 \
--n_heads 8 \
--n_layers 8 \
--mlp_ratio 2 \
--slice_num 32 \
--ntrain 20 \
--ntest 50 \
--batch-size 1 \
--epochs 20 \
--eval 0 \
--save_name craft_geopt_8layers_n20 \
--finetune 1 \
--finetune_name GeoPT_8layers

